import './globals.css'

import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import ThemeSwitcher from '@/components/toggles/theme-switcher'
import { ThemeProvider } from './theme-provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} dark:bg-darkColor1`} >
        <ThemeProvider>
          <header>
            <section className='flex'>
              
              <ThemeSwitcher />
            </section>
          </header>
          {children}
        </ThemeProvider>
      </body>
    </html>
  )
}
